name: C CI for Xenly programming language (makefile for FreeBSD)

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest # The host runner that will start the VM
    steps:
    - uses: actions/checkout@v4
    - name: Run tests in FreeBSD VM
      uses: vmactions/freebsd-vm@v1 # Action to run a FreeBSD VM
      with:
        # Commands run inside the FreeBSD VM
        run: make
