name: C CI for Xenly programming language (Python for macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: python installing test
      run: time python3 install-c.py
    - name: xenly test (1)
      run: time ./xenly examples/hello.xe
    - name: xenlyc test (1)
      run: time ./xenlyc examples/hello.xe -o hello
    - name: hello test (1)
      run: time ./hello
    - name: xenly test (2)
      run: time ./xenly examples/sys_demo.xe
    - name: xenlyc test (2)
      run: time ./xenlyc examples/sys_demo.xe -o sys_demo
    - name: sys_demo test (2)
      run: time ./sys_demo
    - name: xenly test (3)
      run: time ./xenly examples/functional.xe
    - name: xenlyc test (3)
      run: time ./xenlyc examples/functional.xe -o functional
    - name: functional test (3)
      run: time ./functional
    - name: xenly test (4)
      run: time ./xenly examples/math_enhanced_demo.xe
    - name: xenlyc test (4)
      run: time ./xenlyc examples/math_enhanced_demo.xe -o math_enhanced_demo
    - name: math_enhanced_demo test (4)
      run: time ./math_enhanced_demo
    - name: xenly test (5)
      run: time ./xenly examples/test_enum.xe
    - name: xenlyc test (5)
      run: time ./xenlyc examples/test_enum.xe -o test_enum
    - name: test_enum test (5)
      run: time ./test_enum
    - name: xenly test (6)
      run: time ./xenly examples/benchmark_full.xe
    - name: xenlyc test (6)
      run: time ./xenlyc examples/benchmark_full.xe -o benchmark_full
    - name: benchmark_full test (6)
      run: time ./benchmark_full
    - name: xenly test (7)
      run: time ./xenly examples/benchmark.xe
    - name: xenlyc test (7)
      run: time ./xenlyc examples/benchmark.xe -o benchmark
    - name: benchmark test (7)
      run: time ./benchmark
    - name: xenly test (8)
      run: time ./xenly examples/declarative.xe
    - name: xenlyc test (9)
      run: time ./xenlyc examples/declarative.xe -o declarative
    - name: declarative test (9)
      run: time ./declarative
    - name: xenly test (10)
      run: time ./xenly examples/decl_demo.xe
    - name: xenlyc test (10)
      run: time ./xenlyc examples/decl_demo.xe -o decl_demo
    - name: decl_demo test (10)
      run: time ./decl_demo
    - name: xenly test (11)
      run: time ./xenly examples/decl_work.xe
    - name: xenlyc test (11)
      run: time ./xenlyc examples/decl_work.xe -o decl_work
    - name: decl_work test (11)
      run: time ./decl_work
    - name: xenly test (12)
      run: time ./xenly examples/decl_final.xe
    - name: xenlyc test (12)
      run: time ./xenlyc examples/decl_final.xe -o decl_final
    - name: decl_final test (12)
      run: time ./decl_final
    - name: xenly test (13)
      run: time ./xenly examples/fp_immutability.xe
    - name: xenlyc test (13)
      run: time ./xenlyc examples/fp_immutability.xe -o fp_immutability
    - name: fp_immutability test (13)
      run: time ./fp_immutability
