name: C CI for Xenly programming language (makefile for macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: make installing test
      run: make
    - name: xenly test
      run: time ./xenly examples/hello.xe
    - name: xenlyc test
      run: time ./xenlyc examples/hello.xe -o hello
    - name: make clean test
      run: make clean
