name: C CI for Xenly programming language (makefile for macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: make installing test
      run: make
    - name: make clean test
      run: make clean
