name: C CI for Xenly programming language using GO

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23', '1.24', '1.25', '1.26' ]

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: xvm folder
        run: cd xvm
      - name: makefile
        run: make
      - name: return the xenly folder
        run: cd ..
      - name: xenlybyc test
        run: ./xvm/bin/xenlybyc
      - name: xenlyrun test
        run: ./xvm/bin/xenlyrun
