name: C CI for Xenly programming language (makefile for macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    

    - name: make installing test
      run: make
    - name: xenly test (1)
      run: time ./xenly examples/hello.xe
    - name: xenlyc test (1)
      run: time ./xenlyc examples/hello.xe -o hello
    - name: hello test (1)
      run: time ./hello
    - name: xenly test (2)
      run: time ./xenly examples/sys_demo.xe
    - name: xenlyc test (2)
      run: time ./xenlyc examples/sys_demo.xe -o sys_demo
    - name: sys_demo test (2)
      run: time ./sys_demo
    - name: xenly test (3)
      run: time ./xenly examples/functional.xe
    - name: xenlyc test (3)
      run: time ./xenlyc examples/functional.xe -o functional
    - name: functional test (3)
      run: time ./functional
    - name: xenly test (4)
      run: time ./xenly examples/math_enhanced_demo.xe
    - name: xenlyc test (4)
      run: time ./xenlyc examples/math_enhanced_demo.xe -o math_enhanced_demo
    - name: math_enhanced_demo test (4)
      run: time ./math_enhanced_demo
    - name: xenly test (5)
      run: time ./xenly examples/test_enum.xe
    - name: xenlyc test (5)
      run: time ./xenlyc examples/test_enum.xe -o test_enum
    - name: test_enum test (5)
      run: time ./test_enum
    - name: make clean test
      run: make clean
