name: C CI for Xenly programming language using GO for macOS

on: [push]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        go-version: [ '1.21', '1.22', '1.23', '1.24', '1.25', '1.26' ]

    steps:
      - uses: actions/checkout@v5
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version
      - name: xvm folder and makefile
        run: cd xvm && make
      - name: xenlybyc test
        run: ./xvm/bin/xenlybyc
      - name: xenlyrun test
        run: ./xvm/bin/xenlyrun
      - name: hello test (1)
        run: time ./xvm/bin/xenlybyc examples/hello.xe -o hello.xebc
      - name: run hello test (1)
        run: time ./xvm/bin/xenlyrun hello.xebc
      - name: sys_demo test (2)
        run: time ./xvm/bin/xenlybyc examples/sys_demo.xe -o sys_demo.xebc
      - name: run sys_demo test (2)
        run: time ./xvm/bin/xenlyrun sys_demo.xebc
      - name: functional test (3)
        run: time ./xvm/bin/xenlybyc examples/functional.xe -o functional.xebc
      - name: run functional test (3)
        run: time ./xvm/bin/xenlyrun functional.xebc
