name: C CI for Xenly programming language (makefile)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: make test
      run: make test

    - name: make installing test
      run: make
    
    - name: make clean test
      run: make clean
