# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI for Xenly programming language (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build xenly_math.go
      run: go build -o math.dylib -buildmode=c-shared src/libm/math/xenly_math.go
    - name: Build xenly_binary_math.go
      run: go build -o binary_math.dylib -buildmode=c-shared src/libm/binary_math/xenly_binary_math.go
