name: Rust CI for Xenly programming language (Windows)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build xenly_math.rs
      run: rustc --crate-type cdylib -o math.dll src/xenly_math.rs
    - name: Build xenly_binary_math.rs
      run: rustc --crate-type cdylib -o binary_math.dll src/xenly_binary_math.rs
