name: Rust CI for Xenly programming language (macOS)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build xenly_math.rs
      run: rustc --crate-type cdylib -o math.dylib src/libm/math/xenly_math.rs
    - name: Build xenly_binary_math.rs
      run: rustc --crate-type cdylib -o binary_math.dylib src/libm/binary_math/xenly_binary_math.rs
